base_dir = "/home/fave/work/audit"

[env]
eth_rpc_url = "https://eth-mainnet.g.alchemy.com/v2/YourAlchemyKey"
arbitrum_rpc = "https://arb-mainnet.g.alchemy.com/v2/YourAlchemyKey"
private_key = "YourPrivateKey"
etherscan_api_key = "YourEtherscanApiKey"
tenderly_dev_net_rpc_url = "https://api.tenderly.co/api/v1/account/username/project/project/"

[content]
notes = """
# TODO
1. Read READMEs + docs
2. Generate Solidity Metrics report (right click on scope.txt -> Solidity: Metrics)
2. Run `aderyn .`
3. Run `slither .`

# Question until it breaks
- What's the purpose of the protocol?

- What are the business core logics / high-level user stories?

- What are the main components?
                         
- What are the actors and roles?

- What are the assets/tokens involved?

- What can go wrong?

# Entry Points

# Invariants
| Description | Tested | Passed |
|------------|--------|--------|
| Invariant 1 | Yes | Yes |
| Invariant 2 | No | No |


# Glossary

# Resources

# Commands

"""

findings = """
| Level | Impact |
|-------|--------|
| 4. Critical | - Manipulation of governance voting result deviating from voted outcome and resulting in a direct change from intended effect of original results<br>- Direct theft of any user funds, whether at-rest or in-motion, other than unclaimed yield<br>- Direct theft of any user NFTs, whether at-rest or in-motion, other than unclaimed royalties<br>- Permanent freezing of funds<br>- Permanent freezing of NFTs<br>- Unauthorized minting of NFTs<br>- Predictable or manipulable RNG that results in abuse of the principal or NFT<br>- Unintended alteration of what the NFT represents (e.g. token URI, payload, artistic content)<br>- Protocol insolvency |
| 3. High | - Theft of unclaimed yield<br>- Theft of unclaimed royalties<br>- Permanent freezing of unclaimed yield<br>- Permanent freezing of unclaimed royalties<br>- Temporary freezing of funds<br>- Temporary freezing NFTs |
| 2. Medium | - Smart contract unable to operate due to lack of token funds<br>- Block stuffing<br>- Griefing (e.g. no profit motive for an attacker, but damage to the users or the protocol)<br>- Theft of gas<br>- Unbounded gas consumption |
| 1. Low | - Contract fails to deliver promised returns, but doesn't lose value |

# Title

## Summary

## Vulnerability Detail

## Impact

## Code Snippet

## Tool used

Manual Review

## Recommendation



------------------------------------------------------------

# Title
                            
## Impact
Detailed description of the impact of this finding.

## Proof of Concept
Provide direct links to all referenced code in GitHub. Add screenshots, logs, or any other relevant proof that illustrates the concept.

## Tools Used

## Recommended Mitigation Steps



------------------------------------------------------------
"""

